[package]
name = "vessel-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
time.workspace = true
tracing.workspace = true
uuid.workspace = true
vessel-core = { path = "../vessel-core" }
vessel-ledger = { path = "../vessel-ledger" }

[dev-dependencies]
tokio.workspace = true
